"""Validate the required Nakafa Lab scaffold files."""

import pathlib


BEE_CONSTITUENT_PATHS = [
    "data/chemistry/pubchem/bee-constituents/2026-04-27-melittin-properties.json",
    "data/chemistry/pubchem/bee-constituents/2026-04-27-apamin-properties.json",
    "data/chemistry/pubchem/bee-constituents/2026-04-27-10-hda-properties.json",
    "data/chemistry/pubchem/bee-constituents/2026-04-27-cape-properties.json",
    "data/chemistry/pubchem/bee-constituents/2026-04-27-chrysin-properties.json",
    "data/chemistry/pubchem/bee-constituents/2026-04-27-pinocembrin-properties.json",
    "data/chemistry/pubchem/bee-constituents/2026-04-27-quercetin-properties.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-melittin-search.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-apamin-search.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-10-hda-search.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-cape-search.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-chrysin-search.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-pinocembrin-search.json",
    "data/chemistry/chembl/bee-constituents/2026-04-27-quercetin-search.json",
    "data/literature/pubmed/2026-04-27-melittin-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-apamin-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-10-hda-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-cape-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-chrysin-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-pinocembrin-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-quercetin-thalassemia-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-quercetin-beta-thalassemia-major.json",
    "data/literature/pubmed/2026-04-27-quercetin-thalassemia-selected-abstracts.xml",
    "data/registries/clinicaltrials/2026-04-27-quercetin-thalassemia-trials.json",
    "data/literature/pubmed/2026-04-27-curcuminoid-hbf-beta-thalassemia-hbe.json",
    "data/literature/pubmed/2026-04-27-curcumin-thalassemia-major-hbe.json",
    "data/literature/pubmed/2026-04-27-curcuminoid-thalassemia-selected-abstracts.xml",
    "data/registries/clinicaltrials/2026-04-27-curcumin-thalassemia-trials.json",
    "data/literature/pubmed/2026-04-27-curcuminoid-hbf-esummary.json",
    "data/literature/pubmed/2026-04-27-curcuminoid-trienone-pubmed-to-pmc.json",
    "data/literature/pubmed/2026-04-27-curcuminoid-trienone-pmc-oa.xml",
    "data/literature/fulltext/nature/2026-04-27-nuamsee-2021-curcuminoid-trienone.html",
    "data/literature/fulltext/nature/2026-04-27-nuamsee-2021-curcuminoid-trienone-pmc.html",
    "data/chemistry/pubchem/curcuminoid-analogs/2026-04-27-curcumin-properties.json",
    "data/chemistry/pubchem/curcuminoid-analogs/2026-04-27-demethoxycurcumin-properties.json",
    "data/chemistry/pubchem/curcuminoid-analogs/2026-04-27-bis-demethoxycurcumin-properties.json",
    "data/chemistry/chembl/curcuminoid-analogs/2026-04-27-curcumin-search.json",
    "data/chemistry/chembl/curcuminoid-analogs/2026-04-27-demethoxycurcumin-search.json",
    "data/chemistry/chembl/curcuminoid-analogs/2026-04-27-bis-demethoxycurcumin-search.json",
    "data/chemistry/chembl/curcuminoid-analogs/2026-04-27-t-cur-search.json",
    "data/chemistry/chembl/curcuminoid-analogs/2026-04-27-t-dmc-search.json",
    "data/chemistry/chembl/curcuminoid-analogs/2026-04-27-t-bdmc-search.json",
]

REQUIRED_PATHS = [
    "README.md",
    "AGENTS.md",
    "docs/research-protocol.md",
    "docs/next-steps.md",
    "docs/parallel-research-tracks.md",
    "docs/discovery-pipeline.md",
    "docs/zed-latex.md",
    ".zed/tasks.json",
    "data/README.md",
    "data/literature/pubmed/2026-04-26-bcl11a-hbf-beta-thalassemia.json",
    "data/literature/pubmed/2026-04-26-hbf-assay-screening.json",
    "data/literature/pubmed/2026-04-26-hemolysis-assay-safety.json",
    "data/literature/pubmed/2026-04-27-tdt-alloimmunization-autoimmunization.json",
    "data/literature/pubmed/2026-04-27-tdt-direct-antiglobulin-autoantibodies.json",
    "data/literature/pubmed/2026-04-27-thalassemia-antigen-matching.json",
    "data/literature/pubmed/2026-04-26-hydroxyurea-beta-thalassemia.json",
    "data/literature/pubmed/2026-04-27-bee-venom-adverse-events.json",
    "data/literature/pubmed/2026-04-27-melittin-erythrocyte-hemolysis.json",
    "data/literature/pubmed/2026-04-27-melittin-hbf-gap.json",
    "data/literature/pubmed/2026-04-26-propolis-red-cell-oxidative-stress.json",
    "data/literature/pubmed/2026-04-27-royal-jelly-hbf-gap.json",
    "data/literature/pubmed/2026-04-27-royal-jelly-oxidative-stress.json",
    "data/literature/pubmed/2026-04-27-exagamglogene-autotemcel-beta-thalassemia.json",
    "data/literature/pubmed/2026-04-27-betibeglogene-autotemcel-beta-thalassemia.json",
    "data/literature/pubmed/2026-04-27-indonesia-thalassemia-gene-therapy.json",
    "data/literature/pubmed/2026-04-27-indonesia-thalassemia-access.json",
    "data/literature/pubmed/2026-04-27-indonesia-beta-thalassemia-mutations.json",
    "data/literature/pubmed/2026-04-27-hbe-beta-thalassemia-hydroxyurea-xmni.json",
    "data/literature/pubmed/2026-04-27-hbe-beta-thalassemia-hbf-modifiers.json",
    "data/literature/pubmed/2026-04-27-hbf-regulator-targets.json",
    "data/literature/pubmed/2026-04-27-lsd1-hbf-induction.json",
    "data/literature/pubmed/2026-04-27-hdac-hbf-induction.json",
    "data/literature/pubmed/2026-04-27-decitabine-hbf-beta-thalassemia.json",
    "data/literature/pubmed/2026-04-26-sirolimus-beta-thalassemia.json",
    "data/literature/pubmed/2026-04-26-thalidomide-beta-thalassemia.json",
    "data/chemistry/pubchem/2026-04-27-hydroxyurea-properties.json",
    "data/chemistry/pubchem/2026-04-27-decitabine-properties.json",
    "data/chemistry/pubchem/2026-04-27-sirolimus-properties.json",
    "data/chemistry/pubchem/2026-04-27-curcumin-properties.json",
    "data/chemistry/chembl/2026-04-27-hydroxyurea-search.json",
    "data/chemistry/chembl/2026-04-27-decitabine-search.json",
    "data/chemistry/chembl/2026-04-27-sirolimus-search.json",
    "data/chemistry/chembl/2026-04-27-rapamycin-search.json",
    "data/chemistry/chembl/2026-04-27-sirolimus-rapamycin-search.json",
    "data/chemistry/chembl/2026-04-27-curcumin-search.json",
    *BEE_CONSTITUENT_PATHS,
    "data/registries/clinicaltrials/2026-04-27-gene-therapy-beta-thalassemia.json",
    "data/registries/clinicaltrials/2026-04-27-indonesia-thalassemia-trials.json",
    "data/registries/clinicaltrials/2026-04-27-lsd1-beta-thalassemia.json",
    "data/registries/clinicaltrials/2026-04-27-decitabine-beta-thalassemia.json",
    "data/registries/clinicaltrials/2026-04-26-beta-thalassemia-fetal-hemoglobin.json",
    "data/registries/clinicaltrials/2026-04-26-sirolimus-beta-thalassemia.json",
    "data/registries/clinicaltrials/2026-04-26-thalidomide-beta-thalassemia.json",
    "research/thalassemia/README.md",
    "research/thalassemia/assays/2026-04-27-epigenetic-hbf-screen-v0.md",
    "research/thalassemia/case-context/clinician-brief-case-001.md",
    "research/thalassemia/case-context/deidentified-case-001.md",
    "research/thalassemia/findings/2026-04-26-carrier-malaria.md",
    "research/thalassemia/findings/2026-04-26-bee-product-research-scope.md",
    "research/thalassemia/findings/2026-04-26-bee-derived-materials-beyond-honey.md",
    "research/thalassemia/findings/2026-04-26-bee-derived-hbf-evidence-gap.md",
    "research/thalassemia/findings/2026-04-27-bee-constituent-identity-seed-panel.md",
    "research/thalassemia/findings/2026-04-27-quercetin-adjunct-biology-deep-dive.md",
    "research/thalassemia/findings/2026-04-26-clinical-baseline-checklist.md",
    "research/thalassemia/findings/2026-04-27-immune-transfusion-complication-lane.md",
    "research/thalassemia/findings/2026-04-26-clinical-trials-snapshot.md",
    "research/thalassemia/findings/2026-04-26-cure-strategy-map.md",
    "research/thalassemia/findings/2026-04-26-hbf-target-map.md",
    "research/thalassemia/findings/2026-04-26-hbf-target-priority-ranking.md",
    "research/thalassemia/findings/2026-04-26-hbf-reactivation-explainer.md",
    "research/thalassemia/findings/2026-04-26-hydroxyurea-deep-dive.md",
    "research/thalassemia/findings/2026-04-26-sirolimus-deep-dive.md",
    "research/thalassemia/findings/2026-04-26-thalidomide-class-deep-dive.md",
    "research/thalassemia/findings/2026-04-26-propolis-red-cell-deep-dive.md",
    "research/thalassemia/findings/2026-04-27-melittin-bee-venom-hazard-deep-dive.md",
    "research/thalassemia/findings/2026-04-27-royal-jelly-oxidative-stress-deep-dive.md",
    "research/thalassemia/findings/2026-04-27-gene-therapy-access-frontier.md",
    "research/thalassemia/findings/2026-04-27-epigenetic-hbf-target-drilldown.md",
    "research/thalassemia/findings/2026-04-27-chemistry-identity-benchmark-map.md",
    "research/thalassemia/findings/2026-04-27-curcuminoid-hbf-bridge-deep-dive.md",
    "research/thalassemia/findings/2026-04-27-curcuminoid-analog-assay-map.md",
    "research/thalassemia/findings/2026-04-26-assay-ready-hbf-screen.md",
    "research/thalassemia/findings/2026-04-26-assay-funnel-for-cure-discovery.md",
    "research/thalassemia/findings/2026-04-26-disease-taxonomy.md",
    "research/thalassemia/findings/2026-04-27-indonesia-genotype-first-rule.md",
    "research/thalassemia/findings/2026-04-26-indonesia-access-context.md",
    "research/thalassemia/findings/2026-04-26-indonesia-regulatory-access-gap.md",
    "research/thalassemia/findings/2026-04-27-indonesia-access-deep-dive.md",
    "research/thalassemia/findings/2026-04-26-mechanism-priority-map.md",
    "research/thalassemia/findings/2026-04-26-therapy-decision-matrix.md",
    "research/thalassemia/findings/2026-04-26-treatment-landscape.md",
    "research/thalassemia/findings/2026-04-26-repurposed-hbf-inducers.md",
    "research/thalassemia/hypotheses/README.md",
    "research/thalassemia/hypotheses/bee-derived-materials.md",
    "research/thalassemia/hypotheses/cure-oriented-hbf-mimicry.md",
    "research/thalassemia/hypotheses/hbf-small-molecule-triage.md",
    "research/thalassemia/hypotheses/hydroxyurea-evidence-map.md",
    "research/thalassemia/hypotheses/sirolimus-evidence-map.md",
    "research/thalassemia/hypotheses/thalidomide-class-evidence-map.md",
    "research/thalassemia/prioritization/2026-04-26-candidate-ranking.md",
    "research/thalassemia/references/source-registry.md",
    "research/islamic/README.md",
    "research/islamic/findings/2026-04-26-healing-and-caution.md",
    "research/islamic/findings/2026-04-26-theology-of-means.md",
    "research/islamic/findings/2026-04-27-illness-not-blame-guardrail.md",
    "research/islamic/quran/002-al-baqarah/155.md",
    "research/islamic/quran/009-at-tawbah/014.md",
    "research/islamic/quran/010-yunus/057.md",
    "research/islamic/quran/016-an-nahl/068-069.md",
    "research/islamic/quran/017-al-isra/082.md",
    "research/islamic/quran/021-al-anbiya/083-084.md",
    "research/islamic/quran/026-ash-shuara/080.md",
    "research/islamic/quran/041-fussilat/044.md",
    "research/islamic/quran/shifa-root-map.md",
    "research/islamic/quran/quran-wide-healing-search-plan.md",
    "research/islamic/quran/quranic-natural-material-candidate-map.md",
    "paper/main.tex",
    "paper/notes/carrier-malaria.tex",
    "paper/references.bib",
    "pyproject.toml",
    "scripts/fetch_clinical_trials.py",
    "scripts/fetch_pubmed.py",
    "templates/clinician-review-brief-template.md",
    "templates/assay-run-template.md",
    "templates/hypothesis-card-template.md",
    "templates/patient-context-template.md",
]


def main() -> int:
    """Check that required repository files exist."""
    missing = [path for path in REQUIRED_PATHS if not pathlib.Path(path).exists()]

    if missing:
        print("Missing required repo files:")
        for path in missing:
            print(f"- {path}")
        return 1

    print("nakafa.lab scaffold is complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
